## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import pandas as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
samples = np.random.normal(loc=100, scale=15, size= (50,20))
samples

array([[100.58963895,  88.59258087,  92.84014501,  73.39016186,
         79.078682  , 102.56934264,  90.35482732, 103.97094887,
         83.45895863,  98.97185783,  97.93813979,  91.64964437,
         70.12496478, 112.53617104, 117.45568275,  90.69485353,
         76.1882795 ,  86.66041165, 119.79168568, 129.18103091],
       [113.34726089, 102.19350058,  95.40635533,  86.76307089,
         73.69987143,  81.46620418,  96.03918051,  82.12140122,
         89.39165578, 103.82654515,  85.2025918 , 102.82239272,
        108.63275188, 118.61776129,  90.83351309,  79.19260472,
        120.17491804,  89.2658761 , 103.76597042,  94.49560868],
       [ 84.44314473, 112.27694619,  78.90692477,  96.23937125,
        106.12944044,  88.7174902 ,  89.0680381 , 119.5076971 ,
         83.56120745,  91.43479101, 107.06656688, 130.79812066,
         90.07061548,  85.65408275, 109.69999953,  97.4766943 ,
        110.60912626,  91.19046978,  85.69543302, 112.23635674],
       [117.8098832 ,  94.62574368, 107.11033832,  83.65657407,
        105.79369214, 150.62389012,  86.12444465,  96.62966346,
        112.56084739, 108.49218382,  71.64987378,  75.87644673,
        115.60277869, 108.97936397,  86.88112495,  90.25703115,
        111.38287772,  97.80973203,  89.23102967, 139.2785599 ],
       [130.77933827,  99.75505038,  97.19057763, 108.01934905,
        128.35825993,  92.003074  , 110.30049894, 108.22011413,
        103.38536563,  91.74612405,  98.37433558,  93.58959954,
        126.33731815,  95.39707397,  98.17882071,  97.17199477,
        111.03128887,  93.57486773, 107.03146187, 101.93781828],
       [120.53579774,  84.19666043,  69.83788567, 107.56475716,
         87.89492853, 107.12395353,  98.29571084,  99.96767958,
        113.07477029, 102.07998082,  62.77352562,  82.91068604,
         93.81385652, 119.65570585, 112.54739   ,  89.68886061,
        100.63983464,  97.39205201, 121.72622954,  88.96756333],
       [119.21653296, 106.24298476,  97.12074926,  92.34916474,
         83.7442674 ,  98.43147694, 105.09010559,  81.12937125,
        111.91244921, 103.44475117,  81.14518194, 118.00705503,
         83.30435585, 102.12633359,  96.20609108, 123.27994306,
         96.18363337, 102.97723106, 108.53212278, 110.7735826 ],
       [ 94.28430152,  92.10975306, 106.79685374, 103.91130564,
         95.54216849,  91.55742877,  90.99134755,  79.30613248,
         88.17436686,  85.64906009, 100.07444473,  89.78222587,
        114.38989046,  89.15287303,  87.95644073, 108.13744222,
         95.44398097, 123.15949634, 104.53623485, 105.72161115],
       [ 78.51127898,  96.76327871,  98.4822351 ,  95.84178547,
         92.6660033 ,  96.2260876 ,  98.42703042,  97.49357662,
        107.10144578,  86.4971964 , 107.211657  ,  99.00635459,
         96.36356715, 116.37066089,  87.98439401, 125.40961242,
         88.5777509 , 115.35227316,  89.42768538,  89.55844282],
       [122.65500934,  98.62481238, 102.35393913, 128.69904807,
         87.41166021,  77.7737252 ,  96.84508169,  77.62267008,
         81.60297031, 109.41530397, 105.94291485,  74.3857525 ,
         91.21598898,  89.24719213, 109.61550934, 111.27967038,
        103.96331016, 111.38629095,  90.20356739, 102.34366528],
       [ 97.20456159,  93.59361147,  69.26606554,  98.0200816 ,
         97.34934372,  97.02782258,  83.61706589, 111.47034212,
         98.72142629,  98.31258228,  92.88131186, 107.55979368,
         99.67322596, 111.34957529,  95.52336781,  84.33268688,
        112.98286242,  95.07876738, 110.02432   , 108.38163892],
       [130.81026003,  97.9774455 ,  82.93868047,  84.51756413,
         80.70104594,  91.72515718,  92.02046553,  84.16482876,
        102.95979649, 117.31667194,  87.94943968,  83.1333369 ,
        100.29437764, 103.23608177, 103.90181586, 128.40586404,
        103.33012274,  80.28832325, 123.10276837,  92.61002874],
       [108.98981659, 113.89654625, 100.76869346,  74.74244088,
        106.92037869,  86.77864325, 104.31159569, 116.80520925,
        113.91063421, 107.74143028, 104.1762683 ,  87.43939475,
        102.50168595,  97.88390189, 108.75034233, 123.03119887,
         96.86126042,  98.00370408,  92.93684757,  85.25253309],
       [ 82.10260593, 122.71513244,  90.71282101, 100.22718399,
        114.37806962,  96.4879118 , 106.66349121, 107.6185987 ,
         99.79356823,  91.06882461,  92.38281181,  88.35248024,
        101.25677257, 109.46792837, 113.22595299, 104.25264058,
         80.58397727, 112.6645875 , 102.10363176, 135.98414957],
       [103.20136696,  99.45091564, 116.82274033, 103.34745285,
        104.70618784,  76.59680684,  81.00314382, 105.39590083,
         94.59399895,  90.37390176, 117.67828566, 128.41802407,
         97.86072563,  91.04797082,  97.53179611, 113.95780144,
        105.69933374,  94.37682001, 111.0846751 ,  96.03757412],
       [ 95.87662722,  85.13484899, 107.73284573, 112.80301375,
        114.85232122, 114.83186645, 104.59079536, 125.6520445 ,
         95.62814192, 107.57040521,  90.23692593,  96.68063172,
         91.75284581,  81.95612374,  91.77731415,  83.03577304,
         82.65972901, 107.69445234, 115.01521017, 108.46261537],
       [111.64580083,  75.09037018, 113.82792191, 118.3116234 ,
         79.35596488, 107.44872105, 108.2077204 ,  91.22066579,
         98.80030072,  79.24255253,  86.27272751, 116.95605745,
         79.20157729,  90.71316258, 109.84187608,  98.89629649,
         95.05883582,  94.98770072,  90.1275355 ,  81.60957636],
       [107.97445138, 101.61148042, 105.51265118, 117.01718512,
         82.30029201, 108.60012304, 101.79705535, 113.33144667,
         76.48113926,  97.19825898, 107.9566326 ,  95.8164164 ,
        134.17382609, 115.78935795,  95.99536638,  95.59778104,
        114.89923543,  98.48136487, 131.53416229, 113.93266724],
       [ 85.20044965, 107.72119948,  87.51174191,  79.89456191,
        117.01102022, 112.2635698 ,  99.79794854, 108.87569823,
         98.0392781 ,  74.45222349, 113.13248962,  99.33219121,
         82.73440957,  70.08114011, 111.88595738, 115.57996967,
         96.1738855 ,  97.88612013, 118.52737057, 108.53862953],
       [100.36410914,  85.37780267,  87.59746337,  85.77678693,
         96.18058263,  99.11667038, 109.5012328 , 104.90073689,
        118.04651744,  99.32409096,  96.65629491, 114.38530245,
         77.13204917, 115.20661575, 115.40290521,  90.24809857,
        107.81927277,  78.42382893,  95.21374385,  96.62901755],
       [ 91.55771916,  89.19718155, 105.91341948, 107.87151264,
        111.0928636 , 129.46131653,  88.71852428,  61.15524278,
         91.31839688,  86.75375996,  84.77730088, 132.17277701,
         59.87587079, 112.60878951, 118.19010892,  95.95837388,
         89.55487927, 103.81777898,  62.65993221, 103.26286872],
       [107.87962564,  88.92663551,  91.41162967, 114.92735052,
         86.10476373,  94.80697178,  88.93360495, 103.39210148,
        112.80863853, 105.14507105, 100.63084796, 101.80692499,
         95.05087763, 104.49455217, 121.89459798,  97.39422161,
         91.19432508, 106.91597706,  85.80074365, 113.02556414],
       [ 77.60231211, 107.40583141, 107.9948988 , 116.00891281,
         97.57108139,  81.51525678, 124.09570311,  79.75383302,
         85.95584629, 102.60605696, 112.67136291, 127.22850185,
        102.71879709,  94.84161363,  76.30318679, 122.70574006,
         80.78605274,  94.34164349,  74.68857976,  93.97575374],
       [ 73.93646963, 108.12679784, 105.02035165, 106.86042504,
         90.20161006,  80.61080194, 134.2581871 ,  88.25941855,
        103.35449002, 106.84303767,  97.54699739, 115.11681387,
         86.15297028, 103.00434109, 100.28392151, 114.45277936,
         97.35104089, 110.53052878,  85.31285071, 127.92235865],
       [126.24038866, 107.57596965, 121.31831583, 122.29053495,
        118.82224172, 108.90239558,  92.13574095,  89.24038706,
         76.57105423, 125.1605923 ,  55.51287328, 112.17395972,
        135.27396547,  98.51328273, 115.53076268,  69.90342109,
        111.63488358,  97.97873835,  96.74893411,  95.25836006],
       [105.58573957, 122.46967486,  94.24341234, 120.70563094,
        105.38261002,  93.39868582, 102.13917457,  96.7811712 ,
         87.34679494, 110.11582458,  94.75010173,  94.54246102,
        101.45329339,  92.83553651, 130.86563997, 116.07035389,
         91.40927887, 116.7753241 ,  82.92835768,  89.24016966],
       [ 77.58193702, 105.82873314, 113.68712604,  89.41545754,
        103.34611461,  98.17770206, 103.34522873,  91.6899315 ,
         96.34067105, 100.27012541, 100.90224262, 106.65237778,
        111.43100503, 132.143915  ,  77.15795338, 103.51639252,
        128.83429418,  77.77964905,  95.35266695,  86.49144638],
       [121.59209661,  86.64203325, 122.54300365, 121.19082765,
        106.82384833, 116.56881812, 105.03760757, 116.00715613,
         84.66463072, 120.81111373, 115.55268891, 110.5745426 ,
        105.98309695,  90.29072947,  99.51804594, 115.77401117,
        128.58454482,  92.69207418, 106.69195728, 126.31244951],
       [ 87.58268168, 134.20565345, 109.76728801,  82.02034248,
        114.53323814, 100.494712  ,  93.35759109, 100.87287664,
        104.46967766, 103.75846387,  94.5417757 , 100.0360734 ,
         99.73058759,  79.65767983, 127.65392867, 101.11956074,
        105.82393393,  95.93050171, 100.46630748, 119.85357672],
       [ 85.68991631, 111.2917805 ,  71.54274097, 114.59122528,
         94.30957667, 120.3143687 , 107.00214411, 109.80724139,
         82.3296198 ,  71.46486699, 102.92434892,  60.35813314,
        102.872191  , 105.16075298, 109.52690788, 109.90319438,
        133.24301699,  94.68850416, 139.40899916,  75.79046665],
       [ 80.23289811, 116.44562201,  98.99257746, 109.87711138,
        113.58834922,  90.15360449, 135.94343771,  91.78529415,
        122.2799033 ,  68.69868578, 108.07548261,  95.49899316,
        116.41989818,  91.47087221,  98.17844465, 106.54332102,
        106.75945746, 103.46041395,  83.67663061, 121.30451386],
       [ 97.7808925 ,  92.11803477,  97.02465419,  63.08039399,
        115.59303001,  91.72981377,  94.89516597, 104.50587075,
        116.1633035 ,  86.73163249, 118.56443884,  86.50347448,
        115.7438659 ,  82.15297314,  98.83149938,  97.64740129,
        105.57173887,  98.034824  ,  88.61260153, 139.38529933],
       [116.35067715,  93.26394499,  99.00572496,  78.10048392,
        110.47879488, 112.50839521,  96.31386148, 120.88278345,
        106.27346599, 121.07664846, 109.11850521,  96.02298881,
        138.99639277, 126.48561741,  87.33178097, 115.63086753,
         89.65144418, 112.58417679,  90.85305906, 107.21748527],
       [111.19052018, 122.26393139,  91.02175801,  99.8536789 ,
         91.9592208 , 118.2503418 , 103.41589745, 102.35100797,
        115.56972793,  55.81287343, 110.88975126, 105.57648763,
        104.38487424,  65.6506476 , 107.56296865, 115.6560812 ,
        101.54204595, 107.10401208,  77.44906546,  81.14093814],
       [ 76.41361741,  92.85609622, 111.0105739 , 100.06454807,
        122.98268605, 112.53428954,  78.11111864,  97.95777154,
        104.34697366, 105.7710494 ,  89.05922895,  87.28016337,
         86.24326969, 101.78132404, 109.8653366 ,  78.65257359,
         94.72005154,  85.83675157, 115.58819364,  77.46676791],
       [ 96.33127008, 112.61434499,  96.52421788,  83.72390065,
         98.50626887, 118.04799065,  86.15340813,  96.60366727,
        130.24173754, 103.8386335 ,  78.8533987 , 118.84885367,
         98.47319251, 119.09248647, 102.86018338,  78.78722383,
         97.35820823, 109.47313023,  72.50450008,  99.75491451],
       [ 76.44668665, 116.44312696,  95.83791574, 102.86440262,
         89.66123464,  99.36602204, 106.0980892 , 100.09685972,
        112.84163889,  87.41582122, 112.23007327, 107.59419861,
         83.75511737, 107.13837398,  96.12299692,  90.11909322,
         97.12817145, 119.54918524,  89.44170788,  86.72718249],
       [107.96273666, 116.6015301 , 108.64782474, 120.56128541,
        113.51081538, 106.50554179, 123.37400917,  72.93375356,
        110.25081739, 100.64580422,  99.83708376,  83.21815797,
        102.68305862,  86.60251379,  84.41390359,  83.51722301,
        123.72233181,  91.69678113, 107.32050285, 104.38636688],
       [115.35978104,  87.54267061, 118.96820988,  93.98892723,
         82.95544197, 113.07783148, 119.49200739,  89.96734142,
        125.19811358, 101.37927179, 111.29777818, 123.07977475,
        121.87664048,  97.68885442, 109.61128304, 100.81354057,
         98.45848714,  76.16812655, 103.10435616,  99.67128979],
       [ 97.71193893, 104.06744914, 115.46233467,  90.63985146,
         99.96035749,  66.21357399,  97.42167152,  90.48369229,
        123.7075301 ,  80.03197776, 124.38773032, 114.30774458,
         98.05662224,  99.42161858,  95.05039506,  95.10751622,
         90.95436118,  83.4793771 ,  98.56771788,  97.18464121],
       [ 62.29331007,  87.46870444,  87.74456579,  72.38678628,
        110.56926981,  86.0039827 , 102.89858281, 101.61626734,
        127.18273003, 104.99287766, 107.38667335, 101.64691328,
         94.65326019,  60.37586946, 104.34105439, 122.06969624,
         96.40310217, 112.52556996,  89.77379054, 135.96013007],
       [138.44028541,  99.83708178,  80.96590093,  92.163904  ,
         96.36925385,  79.56091866, 104.02773525, 107.30964056,
        106.89318585,  84.69918563, 120.52922951, 128.62831471,
        117.64918532, 114.74993765,  90.42303506,  97.63197247,
        100.45613104,  85.01406661, 100.68767627, 112.86277303],
       [ 73.68783476,  88.00290881,  85.42838259, 109.61411188,
         97.06104593,  97.58114099, 114.2724119 ,  96.06620111,
        133.6592198 , 102.26177098, 104.31279772, 114.11503872,
        112.58464961, 118.71619188, 128.94743539,  83.97719055,
         83.7503942 , 107.6118657 , 110.57960717,  99.54492126],
       [118.74611584,  94.01787034, 131.95612788, 106.06540308,
         82.5852071 , 118.21519261,  94.85720284, 107.47435104,
        118.2791303 ,  63.86505289,  87.37855736,  98.94708345,
        132.98244991,  84.04358803,  91.42999234, 116.71581118,
        105.27090486, 115.17997357, 117.50140017,  79.54708945],
       [111.79087796, 117.26872157,  94.93615941, 122.35574217,
         71.7576469 , 110.14471691, 117.84134733,  80.5707414 ,
         88.04683829,  87.42909342,  99.1003415 ,  84.03867724,
         97.32218052,  84.82444943, 100.62101526,  89.04940181,
        109.64844028,  79.49344201,  85.47197735, 100.40608055],
       [112.57881285,  81.71638887,  91.36249354, 115.2392683 ,
        106.35680854, 109.15793002,  74.38966581, 115.20627539,
         80.86118615,  99.17331932,  85.74149233,  94.54781676,
         90.9485578 , 118.55028944, 103.75149954,  82.47109893,
        101.4264948 ,  85.64064329,  96.31173809,  96.56228392],
       [122.35090691, 111.0299877 ,  99.32394743,  88.46799565,
        101.66866913,  94.33575023,  95.24803715, 117.76300096,
         91.68462707,  99.19073426, 120.29996516, 103.31079259,
        107.6022807 ,  95.69702357,  87.32584545,  83.52376155,
         91.87307283,  69.46804167,  70.3316303 , 100.54827789],
       [119.76020444,  58.62629848, 110.08899173, 104.21999269,
        111.00383304,  91.58579627,  80.64322238, 122.62009958,
         86.83842242,  92.88757051, 104.14429928,  92.92742502,
        105.26150872, 127.25660928,  97.54970122,  91.15194729,
         85.63843713, 104.43757414,  92.14645994, 115.1456127 ],
       [ 87.53814284, 107.61066889, 112.51402085,  98.67700223,
         90.75627924, 113.16520544,  78.15903198,  87.66816048,
        125.5696854 , 108.77629922,  84.84602786,  95.59331194,
        122.89744909,  63.42007044,  79.61490442, 113.46646507,
         94.43493873,  73.70975535,  92.94375753, 106.24919588],
       [111.0660687 ,  76.56452409, 137.47183554,  89.04253297,
        118.71232248,  94.24566207,  96.62229574,  85.57237587,
        108.14940698,  84.39094494, 106.13140506,  81.33653155,
         94.5890364 , 107.16902497, 115.08137433, 107.54879392,
         89.54339335,  77.74237152,  99.71114109,  72.41209605]])

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)
print(mode)
print(mean)
print(median)

ModeResult(mode=array([[62.29331007, 58.62629848, 69.26606554, 63.08039399, 71.7576469 ,
        66.21357399, 74.38966581, 61.15524278, 76.48113926, 55.81287343,
        55.51287328, 60.35813314, 59.87587079, 60.37586946, 76.30318679,
        69.90342109, 76.1882795 , 69.46804167, 62.65993221, 72.41209605]]), count=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))
100.20977650628524
99.67225787357158

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = np.min(samples)
max = np.max(samples)
q1 = np.quantile(samples, .25)
q3 = np.quantile(samples, .75)
iqr = q3 - q1
print(min, max, q1, q3, iqr)

55.51287328335808 150.62389011872256 89.78011703506675 110.57058800758224 20.790470972515493

Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
std_dev = np.std(samples)
print(variance, std_dev)

223.5735964340794 14.952377618094033

Compute the **skewness** and **kurtosis**

In [ ]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)
print(skewness, kurtosis)

[-0.15804031 -0.156227    0.07469833 -0.22971525 -0.09808847  0.49624829
  0.57736128 -0.27071782  0.10753128 -0.58322704 -0.74941786  0.04256784
  0.12960781 -0.35816993  0.14618354  0.01898185  0.54448957 -0.10875378
  0.24134259  0.40647518] [-8.95663424e-01  1.87923949e-01  1.18364481e-01 -7.27639504e-01
 -8.43722252e-01  1.01773988e+00  4.32698543e-01 -3.21636328e-01
 -9.68299212e-01  3.63906531e-01  6.62386331e-01 -3.00062677e-01
  1.35752099e-01 -2.85323498e-01 -4.49803424e-01 -1.00018398e+00
  1.00492417e-01 -7.62958732e-01  8.80071397e-04 -3.40260618e-01]

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([7,8,9,10,11,12,13,14,15,16])
y

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = np.correlate(x,y)
r

array([1750])

## Pandas Correlation Calculation

Run the code below

In [4]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
r, p = stats.pearsonr(x, y)

Call the relevant method  to calculate Pearson's r correlation.

In [5]:
r

0.758640289091187

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [6]:
stats.spearmanr(x, y)

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [7]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [8]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [9]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [10]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [12]:
tips.corr()

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000